import type { CommunityPost, NewsItem } from "./ShopTalkView";

export const fallbackNewsItems: NewsItem[] = [
  {
    id: 1,
    headline: "OSHA expands heat inspections for high-risk outdoor work",
    source: "OSHA",
    date: "Apr 10, 2026",
    summary: "OSHA updated its National Emphasis Program on heat exposure. For contractors, the practical takeaway is simple: document water, rest, shade, acclimatization, and heat-response plans before the first hot-weather site visit.",
    url: "https://www.osha.gov/news/newsreleases/osha-national-news-release/20260410",
    urgency: "Safety",
    thumbnailUrl: "/news/heat-safety.svg",
  },
  {
    id: 2,
    headline: "NFPA previews the biggest changes in the 2026 NEC",
    source: "NFPA",
    date: "Jan 29, 2026",
    summary: "The 2026 National Electrical Code cycle is moving, with changes that can affect planning, estimates, and inspection conversations. Electrical contractors should review updates early instead of waiting until a failed rough-in.",
    url: "https://www.nfpa.org/news-blogs-and-articles/blogs/2026/01/29/2026-nec-key-changes",
    urgency: "Code Update",
    thumbnailUrl: "/news/code-update.svg",
  },
  {
    id: 3,
    headline: "EPA removes the R-410A installation deadline",
    source: "ACHR News",
    date: "May 21, 2026",
    summary: "ACHR News reports that EPA removed the R-410A installation deadline. HVAC contractors still need to watch refrigerant rules closely, but this update changes how some pending equipment installs get scheduled.",
    url: "https://www.achrnews.com/articles/166226-epa-removes-r-410a-installation-deadline",
    urgency: "HVAC",
    thumbnailUrl: "/news/hvac-refrigerant.svg",
  },
  {
    id: 4,
    headline: "ABC says construction must attract 349,000 workers in 2026",
    source: "Associated Builders and Contractors",
    date: "Jan 15, 2026",
    summary: "ABC estimates the industry needs hundreds of thousands of additional workers in 2026. For RIVT users, that is the market signal behind faster crew-building, better profiles, and keeping reliable subs close.",
    url: "https://www.abc.org/News-Media/News-Releases/abc-construction-industry-must-attract-349000-workers-in-2026-despite-macroeconomic-headwinds",
    urgency: "Labor",
    thumbnailUrl: "/news/workforce-market.svg",
  },
  {
    id: 5,
    headline: "Florida electrical contractor renewals and CE reminders",
    source: "DBPR",
    date: "2026",
    summary: "Florida DBPR keeps contractor renewal, continuing education, and board information in one place. Keep this bookmarked before hiring, accepting specialty work, or updating compliance records.",
    url: "https://www2.myfloridalicense.com/electrical-contractors/",
    urgency: "License",
    thumbnailUrl: "/news/license-renewal.svg",
  },
  {
    id: 6,
    headline: "Jacksonville permitting guide for contractors",
    source: "PermitFlow",
    date: "Mar 13, 2026",
    summary: "A contractor-focused look at Jacksonville permitting, review steps, and local process expectations. Useful context before posting work that depends on inspection timing or access to permit records.",
    url: "https://www.permitflow.com/blog/jacksonville-building-permit",
    urgency: "Local",
    thumbnailUrl: "/news/permit-watch.svg",
  },
];
export const communityPromptPosts: CommunityPost[] = [
  {
    id: 1,
    title: "What's the best way to handle a mid-job scope change without losing margin?",
    trade: "General",
    author: "FieldPro",
    badge: "Community Prompt",
    flair: "Question",
    body: "Client keeps adding scope after the contract is signed. Looking for a clean way to document and price change orders on the spot without losing the job or the margin.",
    upvotes: 14,
    downvotes: 1,
    replies: [],
    createdAt: "Jun 2026",
    status: "Needs a pro answer",
  },
  {
    id: 2,
    title: "How are you handling the new OSHA heat rule on outdoor jobs this summer?",
    trade: "General",
    author: "CrewLead",
    badge: "Community Prompt",
    flair: "Discussion",
    body: "OSHA heat rule is coming August 2026. Curious what other crews are doing — written plans, scheduling changes, gear, etc. Share what's actually working in the field.",
    upvotes: 9,
    downvotes: 0,
    replies: [],
    createdAt: "Jun 2026",
    status: "Open",
  },
  {
    id: 3,
    title: "NEC 2023: Are you already pulling permits under the new AFCI expansion rules?",
    trade: "Electrical",
    author: "SparkCheck",
    badge: "Community Prompt",
    flair: "Question",
    body: "Florida is moving to NEC 2023. AFCI now covers all dwelling areas. Have any of you already had inspections fail under the old wiring assumptions? What did you have to change?",
    upvotes: 11,
    downvotes: 2,
    replies: [],
    createdAt: "May 2026",
    status: "Needs a pro answer",
  },
  {
    id: 4,
    title: "Best way to scribe cabinets to stone?",
    trade: "Carpentry",
    author: "FinishCarpenterFL",
    flair: "Question",
    body: "Working on a kitchen with quartz counters and a wavy wall. What's your go-to method for tight, clean scribes?",
    upvotes: 128,
    downvotes: 0,
    commentCount: 67,
    replies: [],
    createdAt: "2h",
    status: "Open",
  },
  {
    id: 5,
    title: "What are you charging for punch-out work?",
    trade: "Electrical",
    author: "ElectricianFL",
    flair: "Discussion",
    body: "Curious what others are billing for small punch-list items on commercial jobs. Per hour? Flat rate?",
    upvotes: 96,
    downvotes: 0,
    commentCount: 54,
    replies: [],
    createdAt: "3h",
    status: "Open",
  },
  {
    id: 6,
    title: "Do I need insurance for side jobs?",
    trade: "Plumbing",
    author: "PlumbingProJax",
    flair: "Question",
    body: "Starting to take on weekend work. Do I need a separate policy or will my current one cover it?",
    upvotes: 71,
    downvotes: 0,
    commentCount: 38,
    replies: [],
    createdAt: "5h",
    status: "Needs a pro answer",
  },
  {
    id: 7,
    title: "Best thinset for large format tile?",
    trade: "Tile",
    author: "TileSetterPro",
    flair: "Question",
    body: "Working on a bathroom with 24x48 porcelain tiles. What's your go-to thinset for coverage and no lippage?",
    upvotes: 42,
    downvotes: 0,
    commentCount: 21,
    replies: [],
    createdAt: "4h",
    status: "Open",
  },
  {
    id: 8,
    title: "How do you price custom built-ins?",
    trade: "Cabinetry",
    author: "CabinetryCo",
    flair: "Discussion",
    body: "Looking for a ballpark on custom built-ins for living rooms. Material plus labor, or square-foot pricing?",
    upvotes: 33,
    downvotes: 0,
    commentCount: 17,
    replies: [],
    createdAt: "5h",
    status: "Open",
  },
];
