import type { CommunityPost } from "./ShopTalkView";
export const communityPromptPosts: CommunityPost[] = [
  {
    id: "prompt-1",
    title: "What's the best way to handle a mid-job scope change without losing margin?",
    trade: "General",
    author: "RIVT",
    badge: "Community Prompt",
    flair: "Question",
    body: "Client keeps adding scope after the contract is signed. Looking for a clean way to document and price change orders on the spot without losing the job or the margin.",
    upvotes: 0,
    downvotes: 0,
    replies: [],
    createdAt: "Starter prompt",
    status: "Needs a pro answer",
    communitySlug: "jacksonville-trades",
  },
  {
    id: "prompt-2",
    title: "How are you handling the new OSHA heat rule on outdoor jobs this summer?",
    trade: "General",
    author: "RIVT",
    badge: "Community Prompt",
    flair: "Discussion",
    body: "Curious what other crews are doing around heat safety: written plans, scheduling changes, gear, and what actually works in the field.",
    upvotes: 0,
    downvotes: 0,
    replies: [],
    createdAt: "Starter prompt",
    status: "Open",
    communitySlug: "jacksonville-trades",
  },
  {
    id: "prompt-3",
    title: "NEC 2023: Are you already pulling permits under the new AFCI expansion rules?",
    trade: "Electrical",
    author: "RIVT",
    badge: "Community Prompt",
    flair: "Question",
    body: "Florida is moving to NEC 2023. AFCI now covers all dwelling areas. Have any of you already had inspections fail under the old wiring assumptions? What did you have to change?",
    upvotes: 0,
    downvotes: 0,
    replies: [],
    createdAt: "Starter prompt",
    status: "Needs a pro answer",
    communitySlug: "electrical-talk",
  },
];
