import type { Job } from "../../types";

export const emptyJob: Job = {
  id: 0,
  title: "No jobs posted yet",
  contractor: "RIVT",
  trade: "Electrical",
  location: "Jacksonville, FL",
  state: "FL",
  distance: 0,
  pay: 0,
  durationHours: 0,
  workType: "Side work",
  difficulty: "Moderate",
  insuranceRequired: false,
  tools: [],
  trustRequirement: "Legal agreement required",
  addressPolicy: "Exact address stays hidden until you accept a job.",
  posted: "Today",
  match: 0,
  rating: 0,
  reviewCount: 0,
  applicants: 0,
  status: "Open",
  summary: "Post the first real job to start building the live Work feed.",
  guidance: ["No active work order yet."],
  risks: ["No active work order"],
  deliverables: ["Job posting", "Acceptance", "Closeout"],
  matchFactors: ["Launch ready"],
};
