export const brandConfig = {
  appName: "RIVT",
  appSlug: "rivt",
  productCategory: "Professional trades network",
  betaLabel: "Founding Jacksonville beta",
  tagline: "Where Skilled Trades Connect",
  heroHeadline: "RIVT",
  heroBody:
    "Where Skilled Trades Connect. Built for contractors, subcontractors, crews, and skilled tradespeople who need work, people, records, and tools in one place.",
  missionLine: "The professional network for skilled trades.",
  pricing: {
    betaPlan: {
      label: "Founding beta",
      summary: "Free while Jacksonville supply and demand are seeded.",
      monthlyUsd: 0,
      dailyFrame: "Free during beta",
    },
    launchPreviewPlan: {
      label: "Paid launch preview",
      summary: "Contractors about $1/day. Tradespeople about $0.50/day.",
      monthlyUsd: null,
      dailyFrame: "$1/day contractor, about $0.50/day tradesperson",
    },
    contractorBase: {
      monthlyUsd: 30,
      dailyFrame: "about $1/day",
    },
    tradespersonBase: {
      monthlyUsd: 15,
      dailyFrame: "about $0.50/day",
    },
    premiumAddon: {
      monthlyUsd: 15,
      dailyFrame: "real-time alerts and priority visibility",
    },
  },
  legal: {
    consentLabel:
      "I accept that I am responsible for required licenses, permits, insurance, local compliance, direct payment terms, and the permanent job record.",
    trustCardTitle: "RIVT network",
    trustCardBody:
      "Users stay responsible for licenses, permits, insurance, compliance, payment, and job terms. ID checks happen before posting or accepting work.",
    idGateLabel: "Government ID check required before posting or accepting work",
    insuranceLabel: "Self-reported insurance",
  },
  theme: {
    modes: {
      light: {
        colorScheme: "light",
        cssVariables: {
          "--bg": "#f5f7f9",
          "--surface": "#ffffff",
          "--surface-soft": "#f1f5f6",
          "--text": "#0f1d23",
          "--muted": "#5a6b74",
          "--faint": "#88959b",
          "--border": "#dfe7eb",
          "--border-strong": "#c8d4da",
          "--nav": "#071015",
          "--nav-deep": "#03080b",
          "--green": "#b8e319",
          "--green-deep": "#4d6900",
          "--green-soft": "#f2ffd2",
          "--blue": "#0b72cf",
          "--blue-soft": "#eaf3ff",
          "--amber": "#d88a16",
          "--amber-soft": "#fff5e3",
          "--danger-soft": "#ffecec",
          "--topbar": "rgba(255, 255, 255, 0.92)",
          "--shadow": "0 18px 44px rgba(16, 35, 50, 0.08)",
          "--shadow-soft": "0 12px 30px rgba(15, 29, 35, 0.06)",
        },
      },
      dark: {
        colorScheme: "dark",
        cssVariables: {
          "--bg": "#0c1215",
          "--surface": "#121b20",
          "--surface-soft": "#18252b",
          "--text": "#edf4f6",
          "--muted": "#9cafb8",
          "--faint": "#748993",
          "--border": "#263840",
          "--border-strong": "#36505a",
          "--nav": "#071014",
          "--nav-deep": "#050a0d",
          "--green": "#2fbd6a",
          "--green-deep": "#93e7b7",
          "--green-soft": "#123322",
          "--blue": "#78bdff",
          "--blue-soft": "#122b42",
          "--amber": "#f4b34b",
          "--amber-soft": "#3b2a12",
          "--danger-soft": "#3a171a",
          "--topbar": "rgba(18, 27, 32, 0.94)",
          "--shadow": "0 20px 50px rgba(0, 0, 0, 0.36)",
          "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.24)",
        },
      },
    },
    palettes: {
      tradeGreen: {
        label: "Trade Green",
        inspiration: "Default field network",
        swatches: ["#149447", "#10252e", "#0b72cf"],
        modes: {
          light: {},
          dark: {},
        },
      },
      jobsiteYellow: {
        label: "Jobsite Yellow",
        inspiration: "Yellow and black jobsite tools",
        swatches: ["#f6c800", "#151515", "#2a2f33"],
        modes: {
          light: {
            "--green": "#d9a900",
            "--green-deep": "#5c4300",
            "--green-soft": "#fff5c2",
            "--blue": "#2b343a",
            "--blue-soft": "#edf1f3",
            "--amber": "#f6c800",
            "--amber-soft": "#fff4b8",
            "--nav": "#131617",
            "--nav-deep": "#080a0b",
          },
          dark: {
            "--green": "#f6c800",
            "--green-deep": "#ffe58a",
            "--green-soft": "#332a08",
            "--blue": "#c5d0d6",
            "--blue-soft": "#1d2529",
            "--amber": "#f6c800",
            "--amber-soft": "#3b310a",
            "--nav": "#080a0b",
            "--nav-deep": "#030404",
          },
        },
      },
      redline: {
        label: "Redline",
        inspiration: "Red and black power tools",
        swatches: ["#d21f2b", "#111111", "#f5f5f5"],
        modes: {
          light: {
            "--green": "#d21f2b",
            "--green-deep": "#8e121b",
            "--green-soft": "#ffe9eb",
            "--blue": "#2f3b44",
            "--blue-soft": "#edf1f4",
            "--amber": "#f19a2a",
            "--amber-soft": "#fff1dd",
            "--nav": "#17191b",
            "--nav-deep": "#0c0d0e",
          },
          dark: {
            "--green": "#f04a56",
            "--green-deep": "#ffb4ba",
            "--green-soft": "#3a1217",
            "--blue": "#c3d0d8",
            "--blue-soft": "#1b252b",
            "--amber": "#f5ad45",
            "--amber-soft": "#392510",
            "--nav": "#0d0d0e",
            "--nav-deep": "#050505",
          },
        },
      },
      systemGreen: {
        label: "System Green",
        inspiration: "Precision green and deep blue shop gear",
        swatches: ["#39b54a", "#132f3b", "#9fe3da"],
        modes: {
          light: {
            "--green": "#26a544",
            "--green-deep": "#096a2a",
            "--green-soft": "#e7f8ea",
            "--blue": "#047c8f",
            "--blue-soft": "#e6f6f8",
            "--amber": "#6aa84f",
            "--amber-soft": "#edf8e8",
            "--nav": "#122c37",
            "--nav-deep": "#07171d",
          },
          dark: {
            "--green": "#5edc75",
            "--green-deep": "#b6f3c1",
            "--green-soft": "#13371d",
            "--blue": "#7fd9e4",
            "--blue-soft": "#112d34",
            "--amber": "#93d47b",
            "--amber-soft": "#203619",
            "--nav": "#06131a",
            "--nav-deep": "#03090d",
          },
        },
      },
      orangeRidge: {
        label: "Orange Ridge",
        inspiration: "Orange and graphite pro tools",
        swatches: ["#e86f24", "#30363a", "#f2f2ee"],
        modes: {
          light: {
            "--green": "#e86f24",
            "--green-deep": "#994012",
            "--green-soft": "#fff0e7",
            "--blue": "#3e5965",
            "--blue-soft": "#edf4f6",
            "--amber": "#f29f3f",
            "--amber-soft": "#fff2df",
            "--nav": "#283033",
            "--nav-deep": "#111719",
          },
          dark: {
            "--green": "#ff8a3d",
            "--green-deep": "#ffc8a4",
            "--green-soft": "#3b1d0d",
            "--blue": "#9ab4bf",
            "--blue-soft": "#19282e",
            "--amber": "#ffae4d",
            "--amber-soft": "#3b260f",
            "--nav": "#111719",
            "--nav-deep": "#070a0b",
          },
        },
      },
      chromeRail: {
        label: "Chrome Rail",
        inspiration: "Shop red, white, and chrome toolboxes",
        swatches: ["#c41230", "#d8dde2", "#20272c"],
        modes: {
          light: {
            "--green": "#c41230",
            "--green-deep": "#85091d",
            "--green-soft": "#ffe8ed",
            "--blue": "#5d6d7a",
            "--blue-soft": "#edf1f4",
            "--amber": "#8b98a5",
            "--amber-soft": "#f0f3f5",
            "--nav": "#20272c",
            "--nav-deep": "#0e1215",
          },
          dark: {
            "--green": "#ff4c64",
            "--green-deep": "#ffb2bf",
            "--green-soft": "#3a1119",
            "--blue": "#c7d0d8",
            "--blue-soft": "#1e2a31",
            "--amber": "#aeb8c0",
            "--amber-soft": "#252d33",
            "--nav": "#0d1114",
            "--nav-deep": "#050708",
          },
        },
      },
      steelBlue: {
        label: "Steel Blue",
        inspiration: "Blue contractor-grade shop systems",
        swatches: ["#1676b7", "#0d2533", "#74c7df"],
        modes: {
          light: {
            "--green": "#1676b7",
            "--green-deep": "#074a79",
            "--green-soft": "#e5f3fb",
            "--blue": "#0b8fac",
            "--blue-soft": "#e3f7fb",
            "--amber": "#3aa3c5",
            "--amber-soft": "#e8f8fb",
            "--nav": "#0d2533",
            "--nav-deep": "#061219",
          },
          dark: {
            "--green": "#5cb7f2",
            "--green-deep": "#b7e0ff",
            "--green-soft": "#102f45",
            "--blue": "#7ad6ee",
            "--blue-soft": "#11323c",
            "--amber": "#69c4de",
            "--amber-soft": "#17323b",
            "--nav": "#061219",
            "--nav-deep": "#03090c",
          },
        },
      },
    },
  },
} as const;

export type TrialPlan =
  | typeof brandConfig.pricing.betaPlan.label
  | typeof brandConfig.pricing.launchPreviewPlan.label;

export type ThemeMode = keyof typeof brandConfig.theme.modes;
export type ThemePalette = keyof typeof brandConfig.theme.palettes;
