export const brandConfig = {
  appName: "RIVT",
  appSlug: "rivt",
  productCategory: "Professional trades network",
  betaLabel: "Founding Jacksonville beta",
  tagline: "Where skilled trades connect",
  heroHeadline: "RIVT",
  heroBody:
    "Built for contractors, subcontractors, crews, and skilled tradespeople who need work, people, records, and tools in one place.",
  missionLine: "The professional network for skilled trades.",
  pricing: {
    betaPlan: {
      label: "Free plan",
      summary: "Free while Jacksonville supply and demand are seeded.",
      monthlyUsd: 0,
      dailyFrame: "Free during beta",
    },
    launchPreviewPlan: {
      label: "Paid launch preview",
      summary: "Contractors about $1/day. Tradespeople about $0.50/day.",
      monthlyUsd: null,
      dailyFrame: "$1/day contractor, about $0.50/day tradesperson",
    },
    contractorBase: {
      monthlyUsd: 30,
      dailyFrame: "about $1/day",
    },
    tradespersonBase: {
      monthlyUsd: 15,
      dailyFrame: "about $0.50/day",
    },
    premiumAddon: {
      monthlyUsd: 15,
      dailyFrame: "real-time alerts and priority visibility",
    },
  },
  legal: {
    consentLabel:
      "I accept that I am responsible for required licenses, permits, insurance, local compliance, direct payment terms, and the permanent job record.",
    trustCardTitle: "RIVT network",
    trustCardBody:
      "Users stay responsible for licenses, permits, insurance, compliance, payment, and job terms. RIVT currently requires verified email and signed platform consent before account setup is complete.",
    idGateLabel: "Email verification and platform consent are required before using RIVT.",
    insuranceLabel: "Self-reported insurance",
  },
  theme: {
    modes: {
      light: {
        colorScheme: "light",
        cssVariables: {
          "--bg": "#f5f7f9",
          "--surface": "#ffffff",
          "--surface-soft": "#f3f5f5",
          "--text": "#0d1114",
          "--muted": "#5f686e",
          "--faint": "#88959b",
          "--border": "#dde2e4",
          "--border-strong": "#c6ced2",
          "--nav": "#080d10",
          "--nav-deep": "#030506",
          "--accent": "#ff4b00",
          "--accent-deep": "#b33400",
          "--accent-soft": "#fff0e8",
          "--blue": "#334f5b",
          "--blue-soft": "#edf3f5",
          "--amber": "#ff8a1d",
          "--amber-soft": "#fff2df",
          "--danger-soft": "#ffecec",
          "--topbar": "rgba(255, 255, 255, 0.92)",
          "--shadow": "0 18px 44px rgba(16, 35, 50, 0.08)",
          "--shadow-soft": "0 12px 30px rgba(15, 29, 35, 0.06)",
        },
      },
      dark: {
        colorScheme: "dark",
        cssVariables: {
          "--bg": "#090d10",
          "--surface": "#11181c",
          "--surface-soft": "#182126",
          "--text": "#f3f6f7",
          "--muted": "#a7b2b8",
          "--faint": "#748993",
          "--border": "#263840",
          "--border-strong": "#36505a",
          "--nav": "#071014",
          "--nav-deep": "#050a0d",
          "--accent": "#ff4b00",
          "--accent-deep": "#ff9a6b",
          "--accent-soft": "#32190b",
          "--blue": "#9ab4bf",
          "--blue-soft": "#17272e",
          "--amber": "#ffae4d",
          "--amber-soft": "#36230d",
          "--danger-soft": "#3a171a",
          "--topbar": "rgba(18, 27, 32, 0.94)",
          "--shadow": "0 20px 50px rgba(0, 0, 0, 0.36)",
          "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.24)",
        },
      },
    },
    legacyPalettes: {
      rivtOrange: {
        label: "RIVT Standard",
        description: "Safety orange, warm concrete, and graphite.",
        inspiration: "The original RIVT field finish",
        swatches: ["#ff4b00", "#101415", "#f7f3eb"],
        modes: {
          light: {
            "--bg": "#f6f2ea",
            "--surface": "#ffffff",
            "--surface-soft": "#eee8de",
            "--text": "#101415",
            "--muted": "#5c625f",
            "--faint": "#818782",
            "--border": "#ddd4c8",
            "--border-strong": "#c9bcac",
            "--accent": "#ff4b00",
            "--accent-deep": "#b33400",
            "--accent-soft": "#fff0e8",
            "--blue": "#31515b",
            "--blue-soft": "#e8f0ef",
            "--amber": "#ff8a1d",
            "--amber-soft": "#fff2df",
            "--nav": "#101415",
            "--nav-deep": "#060809",
            "--topbar": "rgba(255, 255, 255, 0.94)",
            "--shadow": "0 18px 44px rgba(38, 29, 20, 0.11)",
            "--shadow-soft": "0 12px 30px rgba(38, 29, 20, 0.07)",
          },
          dark: {
            "--bg": "#0d1110",
            "--surface": "#151a18",
            "--surface-soft": "#1c2420",
            "--text": "#f5f3ef",
            "--muted": "#abb2ac",
            "--faint": "#77817a",
            "--border": "#29332d",
            "--border-strong": "#3a473e",
            "--accent": "#ff4b00",
            "--accent-deep": "#ff9a6b",
            "--accent-soft": "#32190b",
            "--blue": "#96c0bd",
            "--blue-soft": "#152725",
            "--amber": "#ffae4d",
            "--amber-soft": "#36230d",
            "--nav": "#101415",
            "--nav-deep": "#060809",
            "--topbar": "rgba(16, 20, 21, 0.96)",
            "--shadow": "0 20px 50px rgba(0, 0, 0, 0.38)",
            "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.26)",
          },
        },
      },
      jobsiteYellow: {
        label: "Signal Brass",
        description: "Brass signals, dark ink, and clean work surfaces.",
        inspiration: "High-visibility field marking",
        swatches: ["#bd8500", "#17201f", "#f8f6ee"],
        modes: {
          light: {
            "--bg": "#f7f5ec",
            "--surface": "#ffffff",
            "--surface-soft": "#efeee4",
            "--text": "#17201f",
            "--muted": "#5b625e",
            "--faint": "#7f8782",
            "--border": "#dbd8c8",
            "--border-strong": "#c6c0a7",
            "--accent": "#bd8500",
            "--accent-deep": "#715000",
            "--accent-soft": "#fff2c7",
            "--blue": "#36676b",
            "--blue-soft": "#e4f0ef",
            "--amber": "#bd8500",
            "--amber-soft": "#fff2c7",
            "--nav": "#17201f",
            "--nav-deep": "#0b1010",
            "--topbar": "rgba(255, 255, 255, 0.94)",
            "--shadow": "0 18px 44px rgba(41, 38, 15, 0.12)",
            "--shadow-soft": "0 12px 30px rgba(41, 38, 15, 0.07)",
          },
          dark: {
            "--bg": "#101310",
            "--surface": "#1a1f1b",
            "--surface-soft": "#222820",
            "--text": "#f4f5ed",
            "--muted": "#b2b7aa",
            "--faint": "#828979",
            "--border": "#343b2f",
            "--border-strong": "#49513e",
            "--accent": "#e7ae25",
            "--accent-deep": "#ffdea0",
            "--accent-soft": "#362a0b",
            "--blue": "#85c6c5",
            "--blue-soft": "#163334",
            "--amber": "#e7ae25",
            "--amber-soft": "#362a0b",
            "--nav": "#17201f",
            "--nav-deep": "#0b1010",
            "--topbar": "rgba(23, 32, 31, 0.96)",
            "--shadow": "0 20px 50px rgba(0, 0, 0, 0.4)",
            "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.27)",
          },
        },
      },
      redline: {
        label: "Forge Red",
        description: "Warm forged steel, iron red, and dark graphite.",
        inspiration: "Heat-treated shop steel",
        swatches: ["#ba493e", "#252120", "#f8f3ee"],
        modes: {
          light: {
            "--bg": "#f7f1ed",
            "--surface": "#fffdfb",
            "--surface-soft": "#f1e7e1",
            "--text": "#292120",
            "--muted": "#655b56",
            "--faint": "#8d817a",
            "--border": "#e0d1c8",
            "--border-strong": "#cdb7aa",
            "--accent": "#ba493e",
            "--accent-deep": "#7d2b25",
            "--accent-soft": "#fde7e3",
            "--blue": "#51656a",
            "--blue-soft": "#eaf0ef",
            "--amber": "#c67c3f",
            "--amber-soft": "#fcefdc",
            "--nav": "#252120",
            "--nav-deep": "#100d0d",
            "--topbar": "rgba(255, 253, 251, 0.94)",
            "--shadow": "0 18px 44px rgba(54, 27, 22, 0.12)",
            "--shadow-soft": "0 12px 30px rgba(54, 27, 22, 0.07)",
          },
          dark: {
            "--bg": "#15100f",
            "--surface": "#201817",
            "--surface-soft": "#2a201e",
            "--text": "#f8f0ed",
            "--muted": "#b8aaa4",
            "--faint": "#887b75",
            "--border": "#3c2d29",
            "--border-strong": "#553d37",
            "--accent": "#e46d5f",
            "--accent-deep": "#ffc1b8",
            "--accent-soft": "#3d1916",
            "--blue": "#b0d0cc",
            "--blue-soft": "#18302e",
            "--amber": "#e1a25c",
            "--amber-soft": "#3d2915",
            "--nav": "#252120",
            "--nav-deep": "#100d0d",
            "--topbar": "rgba(37, 33, 32, 0.96)",
            "--shadow": "0 20px 50px rgba(0, 0, 0, 0.42)",
            "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.28)",
          },
        },
      },
      systemGreen: {
        label: "Workshop Green",
        description: "Eucalyptus, deep ink, and quiet precision.",
        inspiration: "Organized bench systems",
        swatches: ["#317d63", "#13262b", "#e9f0e8"],
        modes: {
          light: {
            "--bg": "#f0f4ef",
            "--surface": "#ffffff",
            "--surface-soft": "#e5ede4",
            "--text": "#162522",
            "--muted": "#56645f",
            "--faint": "#7b8983",
            "--border": "#d1ddd3",
            "--border-strong": "#b5c7ba",
            "--accent": "#317d63",
            "--accent-deep": "#17503e",
            "--accent-soft": "#def2e9",
            "--blue": "#356c83",
            "--blue-soft": "#e4f1f4",
            "--amber": "#a67f3e",
            "--amber-soft": "#f7eddc",
            "--nav": "#13262b",
            "--nav-deep": "#071216",
            "--topbar": "rgba(255, 255, 255, 0.94)",
            "--shadow": "0 18px 44px rgba(20, 54, 43, 0.1)",
            "--shadow-soft": "0 12px 30px rgba(20, 54, 43, 0.065)",
          },
          dark: {
            "--bg": "#0c1716",
            "--surface": "#142321",
            "--surface-soft": "#1b2d29",
            "--text": "#eef5ef",
            "--muted": "#a9bab0",
            "--faint": "#71877d",
            "--border": "#2d423b",
            "--border-strong": "#405b50",
            "--accent": "#62bd93",
            "--accent-deep": "#b6efd3",
            "--accent-soft": "#13382c",
            "--blue": "#8bc9df",
            "--blue-soft": "#153039",
            "--amber": "#dbb467",
            "--amber-soft": "#3a2c15",
            "--nav": "#13262b",
            "--nav-deep": "#071216",
            "--topbar": "rgba(19, 38, 43, 0.96)",
            "--shadow": "0 20px 50px rgba(0, 0, 0, 0.42)",
            "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.28)",
          },
        },
      },
      orangeRidge: {
        label: "Copperline",
        description: "Copper, slate, and warm project-paper surfaces.",
        inspiration: "Weathered hardware and field notes",
        swatches: ["#a85e35", "#2b3438", "#f5efe7"],
        modes: {
          light: {
            "--bg": "#f5f0ea",
            "--surface": "#fffdf9",
            "--surface-soft": "#eee5db",
            "--text": "#293235",
            "--muted": "#5f696b",
            "--faint": "#858d8d",
            "--border": "#ddd2c6",
            "--border-strong": "#c7b8a8",
            "--accent": "#a85e35",
            "--accent-deep": "#71391e",
            "--accent-soft": "#f9e7da",
            "--blue": "#416e80",
            "--blue-soft": "#e5f0f3",
            "--amber": "#bd7d35",
            "--amber-soft": "#f8ebd8",
            "--nav": "#2b3438",
            "--nav-deep": "#111719",
            "--topbar": "rgba(255, 253, 249, 0.94)",
            "--shadow": "0 18px 44px rgba(49, 35, 28, 0.11)",
            "--shadow-soft": "0 12px 30px rgba(49, 35, 28, 0.07)",
          },
          dark: {
            "--bg": "#131516",
            "--surface": "#1d2224",
            "--surface-soft": "#252d2e",
            "--text": "#f4f0ec",
            "--muted": "#b2b5b3",
            "--faint": "#7e8786",
            "--border": "#384143",
            "--border-strong": "#4c595b",
            "--accent": "#dc9469",
            "--accent-deep": "#ffc4a3",
            "--accent-soft": "#3d2418",
            "--blue": "#8fc5d5",
            "--blue-soft": "#16313a",
            "--amber": "#e1ae68",
            "--amber-soft": "#3c2b15",
            "--nav": "#2b3438",
            "--nav-deep": "#111719",
            "--topbar": "rgba(43, 52, 56, 0.96)",
            "--shadow": "0 20px 50px rgba(0, 0, 0, 0.4)",
            "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.27)",
          },
        },
      },
      steelBlue: {
        label: "Harbor Blue",
        description: "Cobalt signals, steel, and deep navy chrome.",
        inspiration: "Industrial service systems",
        swatches: ["#2475a6", "#0e2938", "#eef4f6"],
        modes: {
          light: {
            "--bg": "#edf4f6",
            "--surface": "#ffffff",
            "--surface-soft": "#e2edf1",
            "--text": "#132a35",
            "--muted": "#5d6f77",
            "--faint": "#81919a",
            "--border": "#cedee5",
            "--border-strong": "#b4c9d3",
            "--accent": "#2475a6",
            "--accent-deep": "#164c72",
            "--accent-soft": "#e1f0f8",
            "--blue": "#197f95",
            "--blue-soft": "#e0f2f5",
            "--amber": "#7d9cab",
            "--amber-soft": "#e9f1f4",
            "--nav": "#0e2938",
            "--nav-deep": "#06141d",
            "--topbar": "rgba(255, 255, 255, 0.94)",
            "--shadow": "0 18px 44px rgba(17, 55, 73, 0.12)",
            "--shadow-soft": "0 12px 30px rgba(17, 55, 73, 0.07)",
          },
          dark: {
            "--bg": "#09151b",
            "--surface": "#10212a",
            "--surface-soft": "#172d37",
            "--text": "#eef5f7",
            "--muted": "#a6bbc3",
            "--faint": "#718a94",
            "--border": "#29434e",
            "--border-strong": "#3a5b68",
            "--accent": "#67b7e5",
            "--accent-deep": "#b9e1f7",
            "--accent-soft": "#13384c",
            "--blue": "#79d1d9",
            "--blue-soft": "#123238",
            "--amber": "#8db2c1",
            "--amber-soft": "#1b333d",
            "--nav": "#0e2938",
            "--nav-deep": "#06141d",
            "--topbar": "rgba(14, 41, 56, 0.96)",
            "--shadow": "0 20px 50px rgba(0, 0, 0, 0.42)",
            "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.28)",
          },
        },
      },
    },
    appearance: {
      accents: {
        rivtOrange: {
          label: "Orange / black",
          description: "A high-visibility orange system on a black chassis.",
          swatch: "#ff4b00",
          modes: {
            light: { "--accent": "#ff4b00", "--accent-deep": "#b33400", "--accent-soft": "#fff0e8", "--amber": "#ff8a1d", "--amber-soft": "#fff2df" },
            dark: { "--accent": "#ff6a24", "--accent-deep": "#ffb38f", "--accent-soft": "#351a0c", "--amber": "#ffae4d", "--amber-soft": "#36230d" },
          },
        },
        ironRed: {
          label: "Red / black",
          description: "A sharp red system with a hard black frame.",
          swatch: "#e21b23",
          modes: {
            light: { "--accent": "#e21b23", "--accent-deep": "#971319", "--accent-soft": "#ffe7e8", "--amber": "#d96826", "--amber-soft": "#ffeddf" },
            dark: { "--accent": "#ff585e", "--accent-deep": "#ffc4c7", "--accent-soft": "#421416", "--amber": "#f09a5e", "--amber-soft": "#442516" },
          },
        },
        signalBrass: {
          label: "Yellow / black",
          description: "A bright jobsite yellow system on black.",
          swatch: "#ffc20e",
          modes: {
            light: { "--accent": "#d09a00", "--accent-deep": "#594100", "--accent-soft": "#fff5cc", "--amber": "#d09a00", "--amber-soft": "#fff5cc" },
            dark: { "--accent": "#ffd34d", "--accent-deep": "#fff0b3", "--accent-soft": "#443505", "--amber": "#ffd34d", "--amber-soft": "#443505" },
          },
        },
        toolTeal: {
          label: "Teal / black",
          description: "A clean teal system with a black tool-body frame.",
          swatch: "#008f8f",
          modes: {
            light: { "--accent": "#008f8f", "--accent-deep": "#005858", "--accent-soft": "#dcf7f5", "--amber": "#008f8f", "--amber-soft": "#dcf7f5" },
            dark: { "--accent": "#35c5c1", "--accent-deep": "#b6f4f1", "--accent-soft": "#073b3b", "--amber": "#35c5c1", "--amber-soft": "#073b3b" },
          },
        },
        workshopGreen: {
          label: "Green / black",
          description: "A bright green system with a durable dark frame.",
          swatch: "#72b72a",
          modes: {
            light: { "--accent": "#5c9d20", "--accent-deep": "#305711", "--accent-soft": "#edf8dc", "--amber": "#5c9d20", "--amber-soft": "#edf8dc" },
            dark: { "--accent": "#9edb59", "--accent-deep": "#daf7b4", "--accent-soft": "#203b10", "--amber": "#9edb59", "--amber-soft": "#203b10" },
          },
        },
        harborBlue: {
          label: "Blue / black",
          description: "A saturated blue system with black chrome.",
          swatch: "#006fba",
          modes: {
            light: { "--accent": "#006fba", "--accent-deep": "#004878", "--accent-soft": "#e0f1ff", "--amber": "#006fba", "--amber-soft": "#e0f1ff" },
            dark: { "--accent": "#4ca6e0", "--accent-deep": "#b9e4ff", "--accent-soft": "#0c3755", "--amber": "#4ca6e0", "--amber-soft": "#0c3755" },
          },
        },
        custom: {
          label: "My tool color",
          description: "Match the color of the tools you actually carry.",
          swatch: "#ff4b00",
          modes: {
            light: { "--accent": "#ff4b00", "--accent-deep": "#b33400", "--accent-soft": "#fff0e8", "--amber": "#ff8a1d", "--amber-soft": "#fff2df" },
            dark: { "--accent": "#ff6a24", "--accent-deep": "#ffb38f", "--accent-soft": "#351a0c", "--amber": "#ffae4d", "--amber-soft": "#36230d" },
          },
        },
      },
      chromes: {
        graphite: {
          label: "Graphite",
          description: "Neutral black chrome for a familiar RIVT shell.",
          swatch: "#101415",
          modes: {
            light: { "--nav": "#101415", "--nav-deep": "#060809", "--topbar": "rgba(255, 255, 255, 0.94)" },
            dark: { "--nav": "#101415", "--nav-deep": "#060809", "--topbar": "rgba(16, 20, 21, 0.96)" },
          },
        },
        slate: {
          label: "Slate",
          description: "Cool charcoal chrome with a softer edge.",
          swatch: "#2d383c",
          modes: {
            light: { "--nav": "#2d383c", "--nav-deep": "#12191c", "--topbar": "rgba(255, 255, 255, 0.94)" },
            dark: { "--nav": "#2d383c", "--nav-deep": "#12191c", "--topbar": "rgba(45, 56, 60, 0.96)" },
          },
        },
        navy: {
          label: "Deep navy",
          description: "Blue-black chrome for service and field systems.",
          swatch: "#102a38",
          modes: {
            light: { "--nav": "#102a38", "--nav-deep": "#06151e", "--topbar": "rgba(255, 255, 255, 0.94)" },
            dark: { "--nav": "#102a38", "--nav-deep": "#06151e", "--topbar": "rgba(16, 42, 56, 0.96)" },
          },
        },
      },
      canvases: {
        clean: {
          label: "Clean white",
          description: "Bright, neutral surfaces for reading and billing.",
          swatch: "#ffffff",
          modes: {
            light: { "--bg": "#f5f7f9", "--surface": "#ffffff", "--surface-soft": "#f1f4f4", "--text": "#101415", "--muted": "#5f686e", "--faint": "#88959b", "--border": "#dce3e4", "--border-strong": "#c6ced2", "--blue": "#355b6b", "--blue-soft": "#e8f0f4", "--shadow": "0 18px 44px rgba(16, 35, 50, 0.08)", "--shadow-soft": "0 12px 30px rgba(15, 29, 35, 0.06)" },
            dark: { "--bg": "#0d1113", "--surface": "#171d20", "--surface-soft": "#20282b", "--text": "#f3f6f7", "--muted": "#a7b2b8", "--faint": "#748993", "--border": "#2a373c", "--border-strong": "#3b4c52", "--blue": "#8db6c4", "--blue-soft": "#173039", "--shadow": "0 20px 50px rgba(0, 0, 0, 0.36)", "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.24)" },
          },
        },
        paper: {
          label: "Project paper",
          description: "Warm paper surfaces for estimates and daily records.",
          swatch: "#f7f0e7",
          modes: {
            light: { "--bg": "#f6f1e9", "--surface": "#fffdf9", "--surface-soft": "#eee6da", "--text": "#20201e", "--muted": "#63625d", "--faint": "#89877f", "--border": "#dfd4c6", "--border-strong": "#cbbbaa", "--blue": "#426a74", "--blue-soft": "#e5f0ef", "--shadow": "0 18px 44px rgba(51, 39, 29, 0.1)", "--shadow-soft": "0 12px 30px rgba(51, 39, 29, 0.065)" },
            dark: { "--bg": "#151310", "--surface": "#211e19", "--surface-soft": "#2a261f", "--text": "#f6f1e9", "--muted": "#b8b1a6", "--faint": "#857d72", "--border": "#3c362c", "--border-strong": "#524939", "--blue": "#a1c7ca", "--blue-soft": "#183031", "--shadow": "0 20px 50px rgba(0, 0, 0, 0.4)", "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.27)" },
          },
        },
        concrete: {
          label: "Concrete",
          description: "Cool gray surfaces for a restrained jobsite look.",
          swatch: "#e5e7e6",
          modes: {
            light: { "--bg": "#eef0ee", "--surface": "#fbfcfa", "--surface-soft": "#e4e7e4", "--text": "#1b2222", "--muted": "#606968", "--faint": "#858e8d", "--border": "#d3d8d4", "--border-strong": "#b9c1bc", "--blue": "#426a70", "--blue-soft": "#e2efed", "--shadow": "0 18px 44px rgba(27, 35, 34, 0.1)", "--shadow-soft": "0 12px 30px rgba(27, 35, 34, 0.065)" },
            dark: { "--bg": "#111514", "--surface": "#1b201e", "--surface-soft": "#242b28", "--text": "#f0f2ef", "--muted": "#adb5af", "--faint": "#77817b", "--border": "#333c38", "--border-strong": "#48534d", "--blue": "#9bc4c2", "--blue-soft": "#17302e", "--shadow": "0 20px 50px rgba(0, 0, 0, 0.4)", "--shadow-soft": "0 14px 34px rgba(0, 0, 0, 0.27)" },
          },
        },
      },
      densities: {
        field: { label: "Field", description: "Roomy controls for gloves and quick taps.", cssVariables: { "--appearance-space-card": "16px", "--appearance-space-section": "24px", "--appearance-content-gutter": "28px", "--appearance-radius-md": "8px", "--appearance-radius-lg": "14px" } },
        standard: { label: "Standard", description: "Balanced reading and working space.", cssVariables: { "--appearance-space-card": "14px", "--appearance-space-section": "20px", "--appearance-content-gutter": "24px", "--appearance-radius-md": "8px", "--appearance-radius-lg": "12px" } },
        compact: { label: "Compact", description: "More information in a tighter workspace.", cssVariables: { "--appearance-space-card": "12px", "--appearance-space-section": "16px", "--appearance-content-gutter": "18px", "--appearance-radius-md": "6px", "--appearance-radius-lg": "10px" } },
      },
      legacyPaletteMap: {
        rivtOrange: { accent: "rivtOrange", chrome: "graphite", canvas: "paper" },
        jobsiteYellow: { accent: "signalBrass", chrome: "graphite", canvas: "clean" },
        redline: { accent: "ironRed", chrome: "graphite", canvas: "paper" },
        systemGreen: { accent: "workshopGreen", chrome: "navy", canvas: "concrete" },
        orangeRidge: { accent: "rivtOrange", chrome: "slate", canvas: "paper" },
        steelBlue: { accent: "harborBlue", chrome: "navy", canvas: "clean" },
      },
    },
  },
} as const;

export type TrialPlan =
  | typeof brandConfig.pricing.betaPlan.label
  | typeof brandConfig.pricing.launchPreviewPlan.label;

export type ThemeMode = keyof typeof brandConfig.theme.modes;
export type ThemeAccent = keyof typeof brandConfig.theme.appearance.accents;
export type ThemeChrome = keyof typeof brandConfig.theme.appearance.chromes;
export type ThemeCanvas = keyof typeof brandConfig.theme.appearance.canvases;
export type ThemeDensity = keyof typeof brandConfig.theme.appearance.densities;
