import type { Job, Talent } from "./types";

export const jobs: Job[] = [
  {
    id: 101,
    title: "Panel trim-out for kitchen remodel",
    contractor: "Harborline Builders",
    trade: "Electrical",
    location: "Brooklyn, NY",
    state: "NY",
    distance: 4.8,
    pay: 640,
    durationHours: 7,
    workType: "Inspection prep",
    difficulty: "Advanced",
    insuranceRequired: true,
    tools: ["Torque screwdriver", "Label maker", "Voltage tester"],
    trustRequirement: "Legal agreement required",
    addressPolicy: "Full address hidden until both parties confirm.",
    posted: "Today",
    match: 94,
    rating: 4.9,
    reviewCount: 128,
    applicants: 7,
    status: "Shortlisting",
    summary:
      "Finish circuit labeling, install GFCI protection, and upload completion photos after cabinet installation.",
    guidance: [
      "City/state only until accepted",
      "Hiring contractor remains contractor of record",
      "Completion photos unlock review prompts",
    ],
    risks: ["Occupied home", "Inspection window", "Tight panel clearance"],
    deliverables: [
      "Panel schedule photo",
      "Before/after work photos",
      "Completion photo set",
    ],
    matchFactors: [
      "Electrical trim-out history",
      "Within 5 miles",
      "Tools already owned",
      "Legal agreement ready",
    ],
  },
  {
    id: 102,
    title: "Rough-in PEX lines for basement bath",
    contractor: "Northstar Renovation",
    trade: "Plumbing",
    location: "Jersey City, NJ",
    state: "NJ",
    distance: 8.6,
    pay: 780,
    durationHours: 8,
    workType: "Side work",
    difficulty: "Moderate",
    insuranceRequired: false,
    tools: ["PEX expander", "Crimp gauges", "Core drill"],
    trustRequirement: "ID check required",
    addressPolicy: "Full address hidden until both parties confirm.",
    posted: "2h ago",
    match: 88,
    rating: 4.8,
    reviewCount: 84,
    applicants: 4,
    status: "Open",
    summary:
      "Run hot/cold supply, set valve bodies, and leave pressure-test notes for the contractor record.",
    guidance: [
      "ID check required before accepting",
      "Payment handled directly between parties",
      "Water shutoff notice stays in job thread",
    ],
    risks: ["Shared shutoff", "Concrete coring", "Moisture history"],
    deliverables: [
      "Pressure test record",
      "Valve body photo set",
      "Permit card update",
    ],
    matchFactors: ["PEX portfolio match", "Evening availability", "Rate in range", "Clear completion notes"],
  },
  {
    id: 103,
    title: "Mini-split condenser relocation",
    contractor: "Keystone Mechanical",
    trade: "HVAC",
    location: "Stamford, CT",
    state: "CT",
    distance: 16.4,
    pay: 920,
    durationHours: 6,
    workType: "Emergency",
    difficulty: "Expert",
    insuranceRequired: true,
    tools: ["Vacuum pump", "Micron gauge", "Recovery machine"],
    trustRequirement: "ID check required",
    addressPolicy: "Full address hidden until both parties confirm.",
    posted: "Yesterday",
    match: 82,
    rating: 4.7,
    reviewCount: 62,
    applicants: 3,
    status: "Open",
    summary:
      "Recover charge, relocate outdoor unit to side yard pad, extend line set, evacuate, and recommission.",
    guidance: [
      "Specialty credentials shown on profile",
      "Customer address unlocks after mutual confirmation",
      "Startup readings attached to completion record",
    ],
    risks: ["Refrigerant recovery", "HOA clearance", "Weather exposure"],
    deliverables: [
      "Refrigerant recovery log",
      "Startup readings",
      "Line-set pressure notes",
    ],
    matchFactors: ["HVAC portfolio depth", "Recovery equipment", "Expert difficulty fit", "Fast response"],
  },
  {
    id: 104,
    title: "Stair landing framing and guardrail blocking",
    contractor: "Bluebeam Homes",
    trade: "Carpentry",
    location: "Queens, NY",
    state: "NY",
    distance: 6.1,
    pay: 520,
    durationHours: 5,
    workType: "Multi-day",
    difficulty: "Challenging",
    insuranceRequired: true,
    tools: ["Framing nailer", "Laser level", "Oscillating saw"],
    trustRequirement: "Completion photos required",
    addressPolicy: "Full address hidden until both parties confirm.",
    posted: "Today",
    match: 79,
    rating: 4.6,
    reviewCount: 51,
    applicants: 9,
    status: "Scheduled",
    summary:
      "Reframe landing opening, add structural blocking for guardrail posts, and photograph concealed fasteners.",
    guidance: [
      "Level 4 work may get fewer early bids",
      "Fastener photos required before cover",
      "Dust containment notes stay on the record",
    ],
    risks: ["Open stairwell", "Occupied hallway", "Finish protection"],
    deliverables: [
      "Fastener photo log",
      "Guardrail blocking photos",
      "Dust containment signoff",
    ],
    matchFactors: ["Stair framing portfolio", "Nearby crew", "Completion photos", "Schedule fit"],
  },
];

export const talent: Talent[] = [
  {
    id: 201,
    name: "Maya Ortiz",
    trade: "Electrical",
    location: "Brooklyn, NY",
    rating: 4.96,
    reviews: 72,
    verified: true,
    identityVerified: true,
    insured: true,
    match: 96,
    rate: 82,
    portfolio: ["Panel schedules", "Kitchen trim-outs", "Inspection packets"],
    tools: ["Torque screwdriver", "Thermal camera", "Label printer"],
    availability: "Tonight + Saturday",
    responseTime: "12 min",
  },
  {
    id: 202,
    name: "Darius Chen",
    trade: "Plumbing",
    location: "Newark, NJ",
    rating: 4.91,
    reviews: 58,
    verified: true,
    identityVerified: true,
    insured: true,
    match: 91,
    rate: 88,
    portfolio: ["Basement rough-ins", "PEX manifolds", "Pressure tests"],
    tools: ["PEX expander", "Inspection camera", "Press tool"],
    availability: "Weekday evenings",
    responseTime: "18 min",
  },
  {
    id: 203,
    name: "Andre Malik",
    trade: "HVAC",
    location: "White Plains, NY",
    rating: 4.88,
    reviews: 44,
    verified: true,
    identityVerified: true,
    insured: false,
    match: 84,
    rate: 96,
    portfolio: ["Mini-splits", "Commissioning", "Load calc notes"],
    tools: ["Vacuum pump", "Micron gauge", "Recovery machine"],
    availability: "Friday",
    responseTime: "24 min",
  },
  {
    id: 204,
    name: "Nora Walsh",
    trade: "Carpentry",
    location: "Queens, NY",
    rating: 4.82,
    reviews: 37,
    verified: true,
    identityVerified: true,
    insured: true,
    match: 86,
    rate: 74,
    portfolio: ["Stair framing", "Finish blocking", "Punch work"],
    tools: ["Framing nailer", "Laser level", "Track saw"],
    availability: "Tomorrow morning",
    responseTime: "31 min",
  },
];

export const tradeOptions = [
  "All trades",
  "Electrical",
  "Plumbing",
  "HVAC",
  "Carpentry",
  "Cabinetry",
  "Painting/Finishing",
  "Welding",
  "Roofing",
  "Flooring",
  "Drywall",
  "Concrete/Masonry",
  "Landscaping",
  "Tile",
  "Insulation",
  "Framing",
  "General Labor",
  "Demolition",
  "Excavation",
  "Fencing",
  "Gutters",
  "Windows/Doors",
  "Siding",
  "Driveways/Pavers",
  "Pool/Spa",
  "Fire Suppression",
  "Low Voltage",
  "Solar",
  "Security Systems",
] as const;

export const difficultyOptions = [
  "Any difficulty",
  "Easy",
  "Moderate",
  "Challenging",
  "Advanced",
  "Expert",
] as const;

export const workTypeOptions = [
  "All work types",
  "Side work",
  "Emergency",
  "Multi-day",
  "Inspection prep",
] as const;

export const radiusOptions = ["Any radius", "5 mi", "10 mi", "25 mi"] as const;
